/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.Messages.Standard;
using geomerty =RosSharp.RosBridgeClient.Messages.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class TwistWithCovarianceStamped : Message
    {
        public const string RosMessageName = "geometry_msgs/TwistWithCovarianceStamped";

        //  This represents an estimated twist with reference coordinate frame and timestamp.
        public Header header { get; set; }
        public geomerty.TwistWithCovariance twist { get; set; }

        public TwistWithCovarianceStamped()
        {
            this.header = new Header();
            this.twist = new geomerty.TwistWithCovariance();
        }

        public TwistWithCovarianceStamped(Header header, geomerty.TwistWithCovariance twist)
        {
            this.header = header;
            this.twist = twist;
        }
    }
}
